version: "3"
services:
  domino:
    image: "domino:10.0.1-centos7"
    volumes:
      - notesdata01:/local
    ports:
      - 8585:8585
      - 1352:1352
    command: "/domino/domstart.sh"
volumes:
  notesdata01: {}
  